name = "fastapi"
compatibility_date = "2024-11-27"

[vars]
UPSTASH_REDIS_REST_TOKEN = 'AbZaAAIjcDEzZjBkNzIxMTQwNjE0MzIwYmIwNTIyZTc0YzZkNDcxMHAxMA'
UPSTASH_REDIS_REST_URL = 'https://infinite-hookworm-46682.upstash.io'

type = "module"  
